### ISSUE TITLE
Tech debt: pypi action not reading new version #

### ISSUE THREAD

**Issue by dogversioning** [smart-on-fhir/cumulus-library-covid#16]
need to look into this if we make another release.

**Comment by mikix** [comment]
This seems to be fine nowadays? I see 2.1.0 on https://pypi.org/project/cumulus-library-covid/ like I expect.

Optimistically closing, but please re-open if I misunderstood.

**Comment by dogversioning** [comment]
i suspect this was fixed in part due to the cutover to `__init__.py` and dynamic versioning in the pyproject.toml.
