### ISSUE TITLE
Symptom prevalence (week/month) counts fail import into Dashboard, likely cause “missing-or-null” checks. 

### ISSUE THREAD

**Issue by comorbidity** [smart-on-fhir/cumulus-library-covid#34]
covid_symptom__count_prevalence_ed_week
covid_symptom__count_prevalence_ed_month

https://github.com/smart-on-fhir/cumulus-library-covid/blob/main/cumulus_library_covid/covid_symptom/counts.sql#L325

**Comment by comorbidity** [comment]
This is a new issue, worked previously and was loaded into Dashboard many times. 
Probable cause: refactoring of counts.py generation of counts.sql ?

**Comment by dogversioning** [comment]
I cannot replicate this. I've done the following:

- Inside a venv, install the latest cumulus-library
- pulled latest main from covid symptoms (should only matter for the manifest targeting of exports)
- configured my enviroment variables to point to HMS ICD athena db
- ran `cumulus-library export -t covid_symptom`
- logged into staging dashboard
- created a new subscription, `mhg test - count prevalance ed month`
- imported `covid_symptom__count_prevalence_ed_month.csv`
- import completed successfully

can you provide more details on what you did?

**Comment by dogversioning** [comment]
Closing this one - with the ongoing hardening work on this around `cumulus_none` and no repeatability steps, it's likely no longer an issue.
